apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: openwebui-data, namespace: openwebui }
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: upcloud-block-storage-hdd
  resources: { requests: { storage: 5Gi } }
